# Generated by Django 4.0.5 on 2022-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_lecture_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
